-- Create "app1_musician" table
CREATE TABLE "public"."app1_musician" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "first_name" character varying(50) NOT NULL,
  "last_name" character varying(50) NOT NULL,
  "instrument" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "app1_album" table
CREATE TABLE "public"."app1_album" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(100) NOT NULL,
  "release_date" date NOT NULL,
  "num_stars" integer NOT NULL,
  "artist_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "app1_album_artist_id_aed0987a_fk_app1_musician_id" FOREIGN KEY ("artist_id") REFERENCES "public"."app1_musician" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "app1_album_artist_id_aed0987a" to table: "app1_album"
CREATE INDEX "app1_album_artist_id_aed0987a" ON "public"."app1_album" ("artist_id");
-- Create "app2_user" table
CREATE TABLE "public"."app2_user" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "first_name" character varying(50) NOT NULL,
  "last_name" character varying(50) NULL,
  "roll" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "app2_blog" table
CREATE TABLE "public"."app2_blog" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(100) NOT NULL,
  "created_at" date NOT NULL,
  "num_stars" integer NOT NULL,
  "author_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "app2_blog_author_id_1675e606_fk_app2_user_id" FOREIGN KEY ("author_id") REFERENCES "public"."app2_user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "app2_blog_author_id_1675e606" to table: "app2_blog"
CREATE INDEX "app2_blog_author_id_1675e606" ON "public"."app2_blog" ("author_id");
